/* The following code was generated by JFlex 1.6.1 */

package br.com.speedrun.lexicalanalyzer;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/Bruno Moura/Documents/GitHub/ActionScriptLexicalAnalyzer/src/br/com/speedrun/lexicalanalyzer/action_script.lex</tt>
 */
public class LexicalAnalyzer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\1\1\65\1\65\1\1\22\0\1\42\1\25\3\0"+
    "\1\22\1\27\1\0\1\7\1\10\1\21\1\17\1\6\1\20\1\5"+
    "\1\4\1\31\11\3\1\16\1\15\1\26\1\23\1\24\2\0\1\2"+
    "\1\63\13\2\1\64\4\2\1\62\7\2\1\11\1\0\1\12\1\0"+
    "\1\2\1\0\1\34\1\57\1\32\1\50\1\43\1\37\1\52\1\44"+
    "\1\36\1\2\1\55\1\33\1\53\1\45\1\40\1\54\1\2\1\41"+
    "\1\35\1\46\1\51\1\56\1\60\1\47\1\61\1\2\1\13\1\30"+
    "\1\14\7\0\1\65\u1fa2\0\1\65\1\65\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\1\1\2\1\4\24\3\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\10\3\1\47\16\3\1\50\17\3"+
    "\1\51\1\52\1\53\1\54\5\3\1\55\4\3\1\56"+
    "\3\3\1\57\11\3\1\60\6\3\1\61\4\3\1\62"+
    "\7\3\1\63\15\3\1\0\3\3\1\64\3\3\1\65"+
    "\1\66\1\67\3\3\1\0\1\70\5\3\1\71\4\3"+
    "\1\72\1\73\1\74\1\3\1\75\1\3\1\76\5\3"+
    "\1\77\1\100\1\0\6\3\1\101\2\3\1\0\4\3"+
    "\1\102\1\103\4\3\1\104\1\105\4\3\1\106\1\3"+
    "\1\0\2\3\1\107\1\3\1\110\3\3\1\0\3\3"+
    "\1\111\1\112\1\3\1\113\1\3\1\114\3\3\1\115"+
    "\1\0\2\3\1\116\1\3\1\117\1\120\1\0\1\121"+
    "\1\122\1\3\1\123\1\124\1\3\1\125\1\3\1\126"+
    "\1\127\1\130\1\3\1\0\1\3\1\131\1\3\1\132"+
    "\1\0\1\133\1\134\3\0\1\135";

  private static int [] zzUnpackAction() {
    int [] result = new int[287];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\66\0\154\0\242\0\330\0\66\0\66"+
    "\0\66\0\66\0\66\0\66\0\66\0\66\0\66\0\u010e"+
    "\0\u0144\0\u017a\0\u01b0\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be"+
    "\0\u02f4\0\u032a\0\66\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438"+
    "\0\u046e\0\u04a4\0\u04da\0\u0510\0\u0546\0\u057c\0\u05b2\0\u05e8"+
    "\0\u061e\0\u0654\0\u068a\0\u06c0\0\u06f6\0\u072c\0\u0762\0\66"+
    "\0\66\0\66\0\66\0\66\0\66\0\66\0\66\0\66"+
    "\0\u0798\0\66\0\u07ce\0\66\0\u0804\0\u083a\0\u0870\0\u08a6"+
    "\0\u08dc\0\u0912\0\u0948\0\u097e\0\u09b4\0\u09ea\0\154\0\u0a20"+
    "\0\u0a56\0\u0a8c\0\u0ac2\0\u0af8\0\u0b2e\0\u0b64\0\u0b9a\0\u0bd0"+
    "\0\u0c06\0\u0c3c\0\u0c72\0\u0ca8\0\u0cde\0\154\0\u0d14\0\u0d4a"+
    "\0\u0d80\0\u0db6\0\u0dec\0\u0e22\0\u0e58\0\u0e8e\0\u0ec4\0\u0efa"+
    "\0\u0f30\0\u0f66\0\u0f9c\0\u0fd2\0\u1008\0\66\0\66\0\66"+
    "\0\66\0\u103e\0\u1074\0\u10aa\0\u10e0\0\u1116\0\154\0\u114c"+
    "\0\u1182\0\u11b8\0\u11ee\0\u1224\0\u125a\0\u1290\0\u12c6\0\u12fc"+
    "\0\u1332\0\u1368\0\u139e\0\u13d4\0\u140a\0\u1440\0\u1476\0\u14ac"+
    "\0\u14e2\0\154\0\u1518\0\u154e\0\u1584\0\u15ba\0\u15f0\0\u1626"+
    "\0\154\0\u165c\0\u1692\0\u16c8\0\u16fe\0\154\0\u1734\0\u176a"+
    "\0\u17a0\0\u17d6\0\u180c\0\u1842\0\u1878\0\154\0\u18ae\0\u18e4"+
    "\0\u191a\0\u1950\0\u1986\0\u19bc\0\u19f2\0\u1a28\0\u1a5e\0\u1a94"+
    "\0\u1aca\0\u1b00\0\u1b36\0\u1b6c\0\u1ba2\0\u1bd8\0\u1c0e\0\154"+
    "\0\u1c44\0\u1c7a\0\u1cb0\0\154\0\154\0\154\0\u1ce6\0\u1d1c"+
    "\0\u1d52\0\u1d88\0\154\0\u1dbe\0\u1df4\0\u1e2a\0\u1e60\0\u1e96"+
    "\0\154\0\u1ecc\0\u1f02\0\u1f38\0\u1f6e\0\154\0\154\0\154"+
    "\0\u1fa4\0\154\0\u1fda\0\154\0\u2010\0\u2046\0\u207c\0\u20b2"+
    "\0\u20e8\0\154\0\u211e\0\u2154\0\u218a\0\u21c0\0\u21f6\0\u222c"+
    "\0\u2262\0\u2298\0\154\0\u22ce\0\u2304\0\u233a\0\u2370\0\u23a6"+
    "\0\u23dc\0\u2412\0\154\0\154\0\u2448\0\u247e\0\u24b4\0\u24ea"+
    "\0\154\0\154\0\u2520\0\u2556\0\u258c\0\u25c2\0\154\0\u25f8"+
    "\0\u262e\0\u2664\0\u269a\0\154\0\u26d0\0\154\0\u2706\0\u273c"+
    "\0\u2772\0\u27a8\0\u27de\0\u2814\0\u284a\0\154\0\154\0\u2880"+
    "\0\154\0\u28b6\0\154\0\u28ec\0\u2922\0\u2958\0\154\0\u298e"+
    "\0\u29c4\0\u29fa\0\154\0\u2a30\0\154\0\154\0\u2a66\0\154"+
    "\0\154\0\u2a9c\0\154\0\154\0\u2ad2\0\154\0\u2b08\0\66"+
    "\0\154\0\154\0\u2b3e\0\u2b74\0\u2baa\0\154\0\u2be0\0\154"+
    "\0\u2c16\0\154\0\154\0\u2c4c\0\u2c82\0\u2cb8\0\66";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[287];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\4\1\36\1\37\1\40"+
    "\1\41\1\42\1\3\1\43\1\4\1\44\1\45\1\4"+
    "\1\46\1\47\1\50\1\4\1\51\1\4\1\52\1\53"+
    "\1\54\1\4\1\55\1\56\1\57\71\0\2\4\25\0"+
    "\11\4\1\0\22\4\4\0\1\5\25\0\1\5\40\0"+
    "\1\60\16\0\1\61\60\0\1\62\66\0\1\63\3\0"+
    "\1\64\62\0\1\65\2\0\1\66\65\0\1\67\65\0"+
    "\1\70\65\0\1\71\65\0\1\72\65\0\1\73\65\0"+
    "\1\74\71\0\1\75\66\0\1\76\37\0\2\4\25\0"+
    "\2\4\1\77\1\100\3\4\1\101\1\4\1\0\22\4"+
    "\3\0\2\4\25\0\3\4\1\102\5\4\1\0\22\4"+
    "\3\0\2\4\25\0\11\4\1\0\1\103\2\4\1\104"+
    "\2\4\1\105\6\4\1\106\4\4\3\0\2\4\25\0"+
    "\6\4\1\107\2\4\1\0\2\4\1\110\5\4\1\111"+
    "\11\4\3\0\2\4\25\0\3\4\1\112\1\4\1\113"+
    "\1\4\1\114\1\4\1\0\6\4\1\115\13\4\3\0"+
    "\2\4\25\0\11\4\1\0\13\4\1\116\6\4\3\0"+
    "\2\4\25\0\11\4\1\0\1\117\21\4\3\0\2\4"+
    "\25\0\2\4\1\120\6\4\1\0\4\4\1\121\15\4"+
    "\3\0\2\4\25\0\3\4\1\122\5\4\1\0\6\4"+
    "\1\123\13\4\3\0\2\4\25\0\10\4\1\124\1\0"+
    "\1\4\1\125\20\4\3\0\2\4\25\0\7\4\1\126"+
    "\1\4\1\0\1\127\15\4\1\130\3\4\3\0\2\4"+
    "\25\0\4\4\1\131\1\132\3\4\1\0\22\4\3\0"+
    "\2\4\25\0\11\4\1\0\1\133\21\4\3\0\2\4"+
    "\25\0\3\4\1\134\4\4\1\135\1\0\6\4\1\136"+
    "\13\4\3\0\2\4\25\0\3\4\1\137\5\4\1\0"+
    "\22\4\3\0\2\4\25\0\10\4\1\140\1\0\22\4"+
    "\3\0\2\4\25\0\5\4\1\141\3\4\1\0\1\4"+
    "\1\142\20\4\3\0\2\4\25\0\11\4\1\0\3\4"+
    "\1\143\16\4\3\0\2\4\25\0\7\4\1\144\1\4"+
    "\1\0\22\4\3\0\2\4\25\0\11\4\1\0\6\4"+
    "\1\145\13\4\24\0\1\146\65\0\1\147\65\0\1\150"+
    "\65\0\1\151\44\0\2\4\25\0\3\4\1\152\5\4"+
    "\1\0\22\4\3\0\2\4\25\0\4\4\1\153\4\4"+
    "\1\0\3\4\1\154\16\4\3\0\2\4\25\0\11\4"+
    "\1\0\2\4\1\155\17\4\3\0\2\4\25\0\11\4"+
    "\1\0\14\4\1\156\5\4\3\0\2\4\25\0\11\4"+
    "\1\0\3\4\1\157\16\4\3\0\2\4\25\0\3\4"+
    "\1\160\5\4\1\0\22\4\3\0\2\4\25\0\11\4"+
    "\1\0\11\4\1\161\10\4\3\0\2\4\25\0\5\4"+
    "\1\162\3\4\1\0\22\4\3\0\2\4\25\0\1\4"+
    "\1\163\7\4\1\0\3\4\1\164\16\4\3\0\2\4"+
    "\25\0\11\4\1\0\11\4\1\165\10\4\3\0\2\4"+
    "\25\0\2\4\1\166\6\4\1\0\22\4\3\0\2\4"+
    "\25\0\11\4\1\0\2\4\1\167\17\4\3\0\2\4"+
    "\25\0\10\4\1\170\1\0\22\4\3\0\2\4\25\0"+
    "\11\4\1\0\2\4\1\171\17\4\3\0\2\4\25\0"+
    "\11\4\1\0\1\172\21\4\3\0\2\4\25\0\11\4"+
    "\1\0\3\4\1\173\16\4\3\0\2\4\25\0\4\4"+
    "\1\174\4\4\1\0\22\4\3\0\2\4\25\0\11\4"+
    "\1\0\3\4\1\175\16\4\3\0\2\4\25\0\11\4"+
    "\1\0\3\4\1\176\4\4\1\177\11\4\3\0\2\4"+
    "\25\0\2\4\1\200\6\4\1\0\22\4\3\0\2\4"+
    "\25\0\11\4\1\0\6\4\1\201\7\4\1\202\3\4"+
    "\3\0\2\4\25\0\5\4\1\203\2\4\1\204\1\0"+
    "\22\4\3\0\2\4\25\0\6\4\1\205\2\4\1\0"+
    "\22\4\3\0\2\4\25\0\11\4\1\0\2\4\1\206"+
    "\17\4\3\0\2\4\25\0\11\4\1\0\1\207\21\4"+
    "\3\0\2\4\25\0\11\4\1\0\2\4\1\210\17\4"+
    "\3\0\2\4\25\0\11\4\1\0\3\4\1\211\16\4"+
    "\3\0\2\4\25\0\1\4\1\212\7\4\1\0\22\4"+
    "\3\0\2\4\25\0\5\4\1\213\1\4\1\214\1\4"+
    "\1\0\22\4\3\0\2\4\25\0\11\4\1\0\14\4"+
    "\1\215\5\4\3\0\2\4\25\0\10\4\1\216\1\0"+
    "\22\4\3\0\2\4\25\0\11\4\1\0\1\217\21\4"+
    "\3\0\2\4\25\0\11\4\1\0\3\4\1\220\16\4"+
    "\3\0\2\4\25\0\5\4\1\221\3\4\1\0\22\4"+
    "\3\0\2\4\25\0\10\4\1\222\1\0\22\4\3\0"+
    "\2\4\25\0\7\4\1\223\1\4\1\0\22\4\3\0"+
    "\2\4\25\0\11\4\1\0\10\4\1\224\11\4\3\0"+
    "\2\4\25\0\4\4\1\225\4\4\1\0\22\4\3\0"+
    "\2\4\25\0\11\4\1\0\1\226\21\4\3\0\2\4"+
    "\25\0\1\4\1\227\7\4\1\0\22\4\3\0\2\4"+
    "\25\0\4\4\1\230\4\4\1\0\3\4\1\231\16\4"+
    "\3\0\2\4\25\0\11\4\1\0\1\232\21\4\3\0"+
    "\2\4\25\0\11\4\1\0\3\4\1\233\16\4\3\0"+
    "\2\4\25\0\11\4\1\0\1\234\21\4\3\0\2\4"+
    "\25\0\11\4\1\0\3\4\1\235\16\4\3\0\2\4"+
    "\25\0\2\4\1\236\6\4\1\0\22\4\3\0\2\4"+
    "\25\0\11\4\1\0\1\237\21\4\3\0\2\4\25\0"+
    "\2\4\1\240\4\4\1\241\1\4\1\0\22\4\3\0"+
    "\2\4\25\0\4\4\1\242\4\4\1\0\22\4\3\0"+
    "\2\4\25\0\3\4\1\243\5\4\1\0\22\4\3\0"+
    "\2\4\25\0\11\4\1\244\22\4\3\0\2\4\25\0"+
    "\1\4\1\245\7\4\1\0\22\4\3\0\2\4\25\0"+
    "\10\4\1\246\1\0\22\4\3\0\2\4\25\0\11\4"+
    "\1\0\6\4\1\247\13\4\3\0\2\4\25\0\11\4"+
    "\1\0\1\250\21\4\3\0\2\4\25\0\11\4\1\0"+
    "\1\251\21\4\3\0\2\4\25\0\5\4\1\252\3\4"+
    "\1\0\22\4\3\0\2\4\25\0\11\4\1\0\1\253"+
    "\21\4\3\0\2\4\25\0\2\4\1\254\6\4\1\0"+
    "\22\4\3\0\2\4\25\0\11\4\1\0\1\255\21\4"+
    "\3\0\2\4\25\0\4\4\1\256\4\4\1\0\22\4"+
    "\3\0\2\4\25\0\7\4\1\257\1\4\1\0\22\4"+
    "\3\0\2\4\25\0\3\4\1\260\5\4\1\0\22\4"+
    "\3\0\2\4\25\0\3\4\1\261\5\4\1\0\22\4"+
    "\3\0\2\4\25\0\11\4\1\262\22\4\3\0\2\4"+
    "\25\0\11\4\1\0\3\4\1\263\16\4\3\0\2\4"+
    "\25\0\11\4\1\0\12\4\1\264\7\4\3\0\2\4"+
    "\25\0\11\4\1\0\13\4\1\265\6\4\3\0\2\4"+
    "\25\0\11\4\1\0\3\4\1\266\16\4\3\0\2\4"+
    "\25\0\2\4\1\267\6\4\1\0\22\4\3\0\2\4"+
    "\25\0\3\4\1\270\5\4\1\0\22\4\3\0\2\4"+
    "\25\0\11\4\1\0\1\4\1\271\20\4\3\0\2\4"+
    "\25\0\2\4\1\272\6\4\1\0\22\4\3\0\2\4"+
    "\25\0\5\4\1\273\3\4\1\0\22\4\3\0\2\4"+
    "\25\0\2\4\1\274\6\4\1\0\22\4\3\0\2\4"+
    "\25\0\11\4\1\0\14\4\1\275\5\4\3\0\2\4"+
    "\25\0\4\4\1\276\4\4\1\0\22\4\3\0\2\4"+
    "\25\0\11\4\1\0\1\4\1\277\20\4\3\0\2\4"+
    "\25\0\11\4\1\0\3\4\1\300\16\4\3\0\2\4"+
    "\25\0\5\4\1\301\3\4\1\0\22\4\3\0\2\4"+
    "\25\0\2\4\1\302\6\4\1\0\22\4\3\0\2\4"+
    "\25\0\5\4\1\303\3\4\1\0\22\4\3\0\2\4"+
    "\25\0\10\4\1\304\1\0\22\4\3\0\2\4\25\0"+
    "\1\4\1\305\7\4\1\0\22\4\3\0\2\4\25\0"+
    "\11\4\1\0\6\4\1\306\13\4\3\0\2\4\25\0"+
    "\10\4\1\307\1\0\22\4\3\0\2\4\25\0\11\4"+
    "\1\0\1\310\21\4\3\0\2\4\25\0\10\4\1\311"+
    "\1\0\22\4\3\0\2\4\25\0\11\4\1\0\1\312"+
    "\21\4\3\0\2\4\25\0\2\4\1\313\6\4\1\0"+
    "\22\4\44\0\1\314\24\0\2\4\25\0\11\4\1\0"+
    "\3\4\1\315\16\4\3\0\2\4\25\0\10\4\1\316"+
    "\1\0\22\4\3\0\2\4\25\0\10\4\1\317\1\0"+
    "\22\4\3\0\2\4\25\0\11\4\1\0\2\4\1\320"+
    "\17\4\3\0\2\4\25\0\11\4\1\0\13\4\1\321"+
    "\6\4\3\0\2\4\25\0\4\4\1\322\4\4\1\0"+
    "\22\4\3\0\2\4\25\0\11\4\1\0\15\4\1\323"+
    "\4\4\3\0\2\4\25\0\11\4\1\0\6\4\1\324"+
    "\13\4\3\0\2\4\25\0\11\4\1\0\10\4\1\325"+
    "\11\4\46\0\1\326\22\0\2\4\25\0\3\4\1\327"+
    "\5\4\1\0\22\4\3\0\2\4\25\0\3\4\1\330"+
    "\5\4\1\0\22\4\3\0\2\4\25\0\11\4\1\0"+
    "\1\331\21\4\3\0\2\4\25\0\5\4\1\332\3\4"+
    "\1\0\22\4\3\0\2\4\25\0\11\4\1\0\12\4"+
    "\1\333\7\4\3\0\2\4\25\0\11\4\1\0\1\334"+
    "\21\4\3\0\2\4\25\0\11\4\1\0\2\4\1\335"+
    "\17\4\3\0\2\4\25\0\11\4\1\0\1\336\21\4"+
    "\3\0\2\4\25\0\11\4\1\0\1\337\21\4\3\0"+
    "\2\4\25\0\11\4\1\0\2\4\1\340\17\4\3\0"+
    "\2\4\25\0\1\4\1\341\7\4\1\0\22\4\3\0"+
    "\2\4\25\0\11\4\1\0\1\4\1\342\20\4\3\0"+
    "\2\4\25\0\11\4\1\0\5\4\1\343\14\4\3\0"+
    "\2\4\25\0\6\4\1\344\2\4\1\0\2\4\1\345"+
    "\17\4\3\0\2\4\25\0\11\4\1\0\10\4\1\346"+
    "\11\4\3\0\2\4\25\0\11\4\1\0\3\4\1\347"+
    "\16\4\3\0\2\4\25\0\2\4\1\350\6\4\1\0"+
    "\22\4\35\0\1\351\33\0\2\4\25\0\5\4\1\352"+
    "\3\4\1\0\22\4\3\0\2\4\25\0\5\4\1\353"+
    "\3\4\1\0\22\4\3\0\2\4\25\0\11\4\1\0"+
    "\2\4\1\354\17\4\3\0\2\4\25\0\11\4\1\0"+
    "\5\4\1\355\14\4\3\0\2\4\25\0\11\4\1\0"+
    "\1\356\21\4\3\0\2\4\25\0\11\4\1\0\11\4"+
    "\1\357\10\4\3\0\2\4\25\0\2\4\1\360\6\4"+
    "\1\0\22\4\3\0\2\4\25\0\5\4\1\361\3\4"+
    "\1\0\22\4\35\0\1\362\33\0\2\4\25\0\11\4"+
    "\1\0\7\4\1\363\12\4\3\0\2\4\25\0\11\4"+
    "\1\0\3\4\1\364\16\4\3\0\2\4\25\0\1\4"+
    "\1\365\7\4\1\0\22\4\3\0\2\4\25\0\1\4"+
    "\1\366\7\4\1\0\22\4\3\0\2\4\25\0\11\4"+
    "\1\0\7\4\1\367\12\4\3\0\2\4\25\0\3\4"+
    "\1\370\5\4\1\0\22\4\3\0\2\4\25\0\10\4"+
    "\1\371\1\0\22\4\3\0\2\4\25\0\11\4\1\0"+
    "\6\4\1\372\13\4\3\0\2\4\25\0\11\4\1\0"+
    "\1\373\21\4\3\0\2\4\25\0\3\4\1\374\5\4"+
    "\1\0\22\4\3\0\2\4\25\0\3\4\1\375\5\4"+
    "\1\0\22\4\3\0\2\4\25\0\11\4\1\0\1\376"+
    "\21\4\3\0\2\4\25\0\11\4\1\0\16\4\1\377"+
    "\3\4\33\0\1\u0100\35\0\2\4\25\0\7\4\1\u0101"+
    "\1\4\1\0\22\4\3\0\2\4\25\0\11\4\1\0"+
    "\5\4\1\u0102\14\4\3\0\2\4\25\0\4\4\1\u0103"+
    "\4\4\1\0\22\4\3\0\2\4\25\0\3\4\1\u0104"+
    "\5\4\1\0\22\4\3\0\2\4\25\0\11\4\1\0"+
    "\3\4\1\u0105\16\4\3\0\2\4\25\0\1\4\1\u0106"+
    "\7\4\1\0\22\4\54\0\1\u0107\14\0\2\4\25\0"+
    "\11\4\1\0\1\u0108\21\4\3\0\2\4\25\0\11\4"+
    "\1\0\1\u0109\21\4\3\0\2\4\25\0\11\4\1\0"+
    "\3\4\1\u010a\16\4\3\0\2\4\25\0\11\4\1\0"+
    "\2\4\1\u010b\17\4\3\0\2\4\25\0\11\4\1\0"+
    "\1\u010c\21\4\3\0\2\4\25\0\1\4\1\u010d\7\4"+
    "\1\0\22\4\3\0\2\4\25\0\2\4\1\u010e\6\4"+
    "\1\0\22\4\3\0\2\4\25\0\11\4\1\0\2\4"+
    "\1\u010f\17\4\45\0\1\u0110\23\0\2\4\25\0\11\4"+
    "\1\0\2\4\1\u0111\17\4\3\0\2\4\25\0\11\4"+
    "\1\0\1\u0112\21\4\3\0\2\4\25\0\1\4\1\u0113"+
    "\7\4\1\0\22\4\44\0\1\u0114\24\0\2\4\25\0"+
    "\11\4\1\0\1\u0115\21\4\3\0\2\4\25\0\11\4"+
    "\1\0\1\u0116\21\4\3\0\2\4\25\0\11\4\1\0"+
    "\3\4\1\u0117\16\4\3\0\2\4\25\0\11\4\1\0"+
    "\1\u0118\21\4\36\0\1\u0119\32\0\2\4\25\0\11\4"+
    "\1\0\5\4\1\u011a\14\4\3\0\2\4\25\0\4\4"+
    "\1\u011b\4\4\1\0\22\4\55\0\1\u011c\45\0\1\u011d"+
    "\63\0\1\u011e\76\0\1\u011f\22\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11502];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\11\11\13\1\1\11\24\1\11\11"+
    "\1\1\1\11\1\1\1\11\51\1\4\11\72\1\1\0"+
    "\15\1\1\0\31\1\1\0\11\1\1\0\22\1\1\0"+
    "\10\1\1\0\15\1\1\0\6\1\1\0\10\1\1\11"+
    "\3\1\1\0\4\1\1\0\2\1\3\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[287];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

private ActionScriptToken createToken(String nome, String value) {
    return new ActionScriptToken(nome, value, yyline, yycolumn);
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicalAnalyzer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 186) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public ActionScriptToken yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("Token inválido em Action Script. \"" + yytext() + "\" Linha: " + yyline + " Coluna: " + yycolumn);
            }
          case 94: break;
          case 2: 
            { return createToken("branco", yytext().equals("\n") ? "\\n" : yytext().equals("\r") ? "\\r" : yytext().equals("\t") ? "\\t" : yytext());
            }
          case 95: break;
          case 3: 
            { return createToken("identificador", yytext());
            }
          case 96: break;
          case 4: 
            { return createToken("inteiro", yytext());
            }
          case 97: break;
          case 5: 
            { return createToken("divisão", yytext());
            }
          case 98: break;
          case 6: 
            { return createToken("ponto", yytext());
            }
          case 99: break;
          case 7: 
            { return createToken("vírgula", yytext());
            }
          case 100: break;
          case 8: 
            { return createToken("parêntese esquerdo", yytext());
            }
          case 101: break;
          case 9: 
            { return createToken("parêntese direito", yytext());
            }
          case 102: break;
          case 10: 
            { return createToken("colchete esquerdo", yytext());
            }
          case 103: break;
          case 11: 
            { return createToken("colchete direito", yytext());
            }
          case 104: break;
          case 12: 
            { return createToken("chave esquerda", yytext());
            }
          case 105: break;
          case 13: 
            { return createToken("chave direita", yytext());
            }
          case 106: break;
          case 14: 
            { return createToken("ponto e vígula", yytext());
            }
          case 107: break;
          case 15: 
            { return createToken("qualificador de tipo", yytext());
            }
          case 108: break;
          case 16: 
            { return createToken("adição", yytext());
            }
          case 109: break;
          case 17: 
            { return createToken("subtração", yytext());
            }
          case 110: break;
          case 18: 
            { return createToken("multiplicação", yytext());
            }
          case 111: break;
          case 19: 
            { return createToken("módulo", yytext());
            }
          case 112: break;
          case 20: 
            { return createToken("atribuição", yytext());
            }
          case 113: break;
          case 21: 
            { return createToken("maior que", yytext());
            }
          case 114: break;
          case 22: 
            { return createToken("NOT lógico", yytext());
            }
          case 115: break;
          case 23: 
            { return createToken("menor que", yytext());
            }
          case 116: break;
          case 24: 
            { return createToken("delimitador de comentário em linha", yytext());
            }
          case 117: break;
          case 25: 
            { return createToken("atribuição de divisão", yytext());
            }
          case 118: break;
          case 26: 
            { return createToken("qualificador de namespace", yytext());
            }
          case 119: break;
          case 27: 
            { return createToken("incremento", yytext());
            }
          case 120: break;
          case 28: 
            { return createToken("atribuição de adição", yytext());
            }
          case 121: break;
          case 29: 
            { return createToken("decremento", yytext());
            }
          case 122: break;
          case 30: 
            { return createToken("atribuição de subtração", yytext());
            }
          case 123: break;
          case 31: 
            { return createToken("atribuição de multiplicação", yytext());
            }
          case 124: break;
          case 32: 
            { return createToken("atribuição de módulo", yytext());
            }
          case 125: break;
          case 33: 
            { return createToken("igualdade", yytext());
            }
          case 126: break;
          case 34: 
            { return createToken("maior ou igual", yytext());
            }
          case 127: break;
          case 35: 
            { return createToken("desigualdade", yytext());
            }
          case 128: break;
          case 36: 
            { return createToken("menor ou igual", yytext());
            }
          case 129: break;
          case 37: 
            { return createToken("AND lógico", yytext());
            }
          case 130: break;
          case 38: 
            { return createToken("OR lógico", yytext());
            }
          case 131: break;
          case 39: 
            { return createToken("if", yytext());
            }
          case 132: break;
          case 40: 
            { return createToken("do", yytext());
            }
          case 133: break;
          case 41: 
            { return createToken("igualdade restrita", yytext());
            }
          case 134: break;
          case 42: 
            { return createToken("desigualdade restrita", yytext());
            }
          case 135: break;
          case 43: 
            { return createToken("AND lógico e atribuição", yytext());
            }
          case 136: break;
          case 44: 
            { return createToken("OR lógico e atribuição", yytext());
            }
          case 137: break;
          case 45: 
            { return createToken("set", yytext());
            }
          case 138: break;
          case 46: 
            { return createToken("int", yytext());
            }
          case 139: break;
          case 47: 
            { return createToken("for", yytext());
            }
          case 140: break;
          case 48: 
            { return createToken("try", yytext());
            }
          case 141: break;
          case 49: 
            { return createToken("get", yytext());
            }
          case 142: break;
          case 50: 
            { return createToken("var", yytext());
            }
          case 143: break;
          case 51: 
            { return createToken("case", yytext());
            }
          case 144: break;
          case 52: 
            { return createToken("else", yytext());
            }
          case 145: break;
          case 53: 
            { return createToken("null", yytext());
            }
          case 146: break;
          case 54: 
            { return createToken("true", yytext());
            }
          case 147: break;
          case 55: 
            { return createToken("this", yytext());
            }
          case 148: break;
          case 56: 
            { return createToken("uint", yytext());
            }
          case 149: break;
          case 57: 
            { return createToken("with", yytext());
            }
          case 150: break;
          case 58: 
            { return createToken("class", yytext());
            }
          case 151: break;
          case 59: 
            { return createToken("catch", yytext());
            }
          case 152: break;
          case 60: 
            { return createToken("const", yytext());
            }
          case 153: break;
          case 61: 
            { return createToken("label", yytext());
            }
          case 154: break;
          case 62: 
            { return createToken("super", yytext());
            }
          case 155: break;
          case 63: 
            { return createToken("false", yytext());
            }
          case 156: break;
          case 64: 
            { return createToken("final", yytext());
            }
          case 157: break;
          case 65: 
            { return createToken("throw", yytext());
            }
          case 158: break;
          case 66: 
            { return createToken("break", yytext());
            }
          case 159: break;
          case 67: 
            { return createToken("while", yytext());
            }
          case 160: break;
          case 68: 
            { return createToken("static", yytext());
            }
          case 161: break;
          case 69: 
            { return createToken("switch", yytext());
            }
          case 162: break;
          case 70: 
            { return createToken("import", yytext());
            }
          case 163: break;
          case 71: 
            { return createToken("return", yytext());
            }
          case 164: break;
          case 72: 
            { return createToken("native", yytext());
            }
          case 165: break;
          case 73: 
            { return createToken("public", yytext());
            }
          case 166: break;
          case 74: 
            { return createToken("String", yytext());
            }
          case 167: break;
          case 75: 
            { return createToken("Number", yytext());
            }
          case 168: break;
          case 76: 
            { return createToken("include", yytext());
            }
          case 169: break;
          case 77: 
            { return createToken("finally", yytext());
            }
          case 170: break;
          case 78: 
            { return createToken("extends", yytext());
            }
          case 171: break;
          case 79: 
            { return createToken("default", yytext());
            }
          case 172: break;
          case 80: 
            { return createToken("dynamic", yytext());
            }
          case 173: break;
          case 81: 
            { return createToken("package", yytext());
            }
          case 174: break;
          case 82: 
            { return createToken("private", yytext());
            }
          case 175: break;
          case 83: 
            { return createToken("Boolean", yytext());
            }
          case 176: break;
          case 84: 
            { return createToken("continue", yytext());
            }
          case 177: break;
          case 85: 
            { return createToken("internal", yytext());
            }
          case 178: break;
          case 86: 
            { return createToken("for each", yytext());
            }
          case 179: break;
          case 87: 
            { return createToken("function", yytext());
            }
          case 180: break;
          case 88: 
            { return createToken("override", yytext());
            }
          case 181: break;
          case 89: 
            { return createToken("interface", yytext());
            }
          case 182: break;
          case 90: 
            { return createToken("namespace", yytext());
            }
          case 183: break;
          case 91: 
            { return createToken("protected", yytext());
            }
          case 184: break;
          case 92: 
            { return createToken("implements", yytext());
            }
          case 185: break;
          case 93: 
            { return createToken("use namespace", yytext());
            }
          case 186: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
